- hosts: webservers
  gather_facts: true
  beorge: true

  roles:
    - role: sslcerts
      vars:
        letsencrypt_email: kishore@ctruh.org
        main_domain_name: ctruh.org
        all_domain_names:
          - ctruh.org
          - www.ctruh.org
        deploy_sample_html: true
